name: Construir y Publicar Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir la imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USER }}/univ-prueba:latest .

      - name: Publicar la imagen Docker
        run: docker push ${{ secrets.DOCKER_USER }}/univ-prueba:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v5

      # 1️⃣ Copiar setup_vm.sh y docker-compose.yml a la VM
      - name: Copiar archivos a la VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "setup_vm.sh,docker-compose.yml"
          target: "/deploy"

      # 2️⃣ Ejecutar setup_vm.sh en la VM
      - name: Ejecutar setup_vm.sh en la VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            chmod +x /deploy/setup_vm.sh
            /deploy/setup_vm.sh ${{ secrets.SSH_USER }}

      # 3️⃣ Ejecutar docker-compose en la VM
      - name: Ejecutar docker-compose en la VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /deploy

            # Login en Docker Hub
            echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

            sudo docker-compose pull
            sudo docker-compose up -d --force-recreate
            sudo docker logout
