name: Construir, Publicar y Desplegar Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir la imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USER }}/univ-prueba:latest .

      - name: Publicar la imagen Docker
        run: docker push ${{ secrets.DOCKER_USER }}/univ-prueba:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v5

      # 1️⃣ Copiar setup_vm.sh y docker-compose.yml a la VM
      - name: Copiar archivos a la VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "setup_vm.sh,docker-compose.yml"
          target: "/home/${{ secrets.SSH_USER }}/deploy"

      # 2️⃣ Ejecutar setup_vm.sh en la VM
      - name: Ejecutar setup_vm.sh en la VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            DEPLOY_PATH="/home/${{ secrets.SSH_USER }}/deploy"
            chmod +x $DEPLOY_PATH/setup_vm.sh
            $DEPLOY_PATH/setup_vm.sh ${{ secrets.SSH_USER }}

      # 3️⃣ Ejecutar docker-compose en la VM
      - name: Ejecutar docker-compose en la VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            DEPLOY_PATH="/home/${{ secrets.SSH_USER }}/deploy"
            cd $DEPLOY_PATH

            DOCKER_USER="${{ secrets.DOCKER_USER }}"
            DOCKER_PASSWORD="${{ secrets.DOCKER_PASSWORD }}"

            echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USER" --password-stdin

            # Detener contenedores existentes
            sudo docker-compose down

            sudo docker-compose pull
            sudo docker-compose up -d --force-recreate
            sudo docker logout

      # 4️⃣ Enviar correo con la URL pública usando App Password
      - name: Enviar email de deploy completado
        uses: dawidd6/action-send-mail@v6
        with:
          connection_url: smtp://{{ secrets.EMAIL_USER }}:${{ secrets.EMAIL_PASSWORD }}@smtp.gmail.com:465
          subject: "Deploy completado ✅"
          body: "El deploy de la aplicación Docker se completó correctamente.\n\nAccede a la aplicación aquí: http://163.176.174.20/"
          to: molinafranz943@gmail.com
          from: ${{ secrets.EMAIL_USER }}
