name: Construir y Publicar Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir la imagen Docker
        run: docker build -t ${{ secrets.DOCKER_USER }}/univ-prueba:latest .

      - name: Publicar la imagen Docker
        run: docker push ${{ secrets.DOCKER_USER }}/univ-prueba:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código (obtener docker-compose.yml, setup_vm.sh)
        uses: actions/checkout@v5

      - name: Ejecutar script de instalación en la VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/tmp
            cp setup_vm.sh ~/tmp/setup_vm.sh || true
            chmod +x ~/tmp/setup_vm.sh
            ~/tmp/setup_vm.sh ${{ secrets.SSH_USER }}
            rm ~/tmp/setup_vm.sh

      # Copiar docker-compose.yml a la VM
      - name: Copiar docker-compose.yml a la VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.yml"
          target: "/home/${{ secrets.SSH_USER }}/deploy"

      - name: Ejecutar docker-compose en la VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            DEPLOY_PATH="/home/${{ secrets.SSH_USER }}/deploy"
            cd $DEPLOY_PATH

            # Descarga la imagen desde Docker Hub
            echo ${{ secrets.DOCKER_PASSWORD }} | sudo docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

            sudo docker-compose pull
            sudo docker-compose up -d --force-recreate
            sudo docker logout
